// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/185c8f30b6464e664cc7cb85240a05b63bea818b/cordova-ionic/index.d.ts
interface CordovaPlugins {
  Keyboard: Ionic.Keyboard;
}
